/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio1a5;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
/**
 *
 * @author USER
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("Notas");
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JBCalcular = new javax.swing.JButton();
        JBLimpiar = new javax.swing.JButton();
        JTNota1 = new javax.swing.JTextField();
        JTNota2 = new javax.swing.JTextField();
        JTNota3 = new javax.swing.JTextField();
        JTNota4 = new javax.swing.JTextField();
        JTNota5 = new javax.swing.JTextField();
        JLNota1 = new javax.swing.JLabel();
        JLNota2 = new javax.swing.JLabel();
        JLNota3 = new javax.swing.JLabel();
        JLNota4 = new javax.swing.JLabel();
        JLNota5 = new javax.swing.JLabel();
        JLPromedio = new javax.swing.JLabel();
        JLDesviacion = new javax.swing.JLabel();
        JLMayor = new javax.swing.JLabel();
        JLMenor = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBCalcular.setText("Calcular");
        JBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCalcularActionPerformed(evt);
            }
        });

        JBLimpiar.setText("Limpiar");
        JBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimpiarActionPerformed(evt);
            }
        });

        JLNota1.setText("Nota 1");

        JLNota2.setText("Nota 2");

        JLNota3.setText("Nota 3");

        JLNota4.setText("Nota 4");

        JLNota5.setText("Nota 5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLMenor)
                    .addComponent(JLMayor)
                    .addComponent(JLDesviacion)
                    .addComponent(JLPromedio)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLNota1)
                            .addComponent(JLNota2)
                            .addComponent(JLNota3)
                            .addComponent(JLNota4)
                            .addComponent(JLNota5))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTNota5, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(JTNota4)
                            .addComponent(JTNota3)
                            .addComponent(JTNota2)
                            .addComponent(JTNota1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(JBCalcular)
                        .addGap(67, 67, 67)
                        .addComponent(JBLimpiar)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNota1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNota2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNota3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNota4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNota5))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCalcular)
                    .addComponent(JBLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(JLPromedio)
                .addGap(18, 18, 18)
                .addComponent(JLDesviacion)
                .addGap(18, 18, 18)
                .addComponent(JLMayor)
                .addGap(18, 18, 18)
                .addComponent(JLMenor)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCalcularActionPerformed
        // TODO add your handling code here:
        Notas notas = new Notas();
        notas.listaNotas[0] = Double.parseDouble(JTNota1.getText());
        notas.listaNotas[1] = Double.parseDouble(JTNota2.getText());
        notas.listaNotas[2] = Double.parseDouble(JTNota3.getText());
        notas.listaNotas[3] = Double.parseDouble(JTNota4.getText());
        notas.listaNotas[4] = Double.parseDouble(JTNota5.getText());
        notas.calcularPromedio(); 
        notas.calcularDesviacion();
        JLPromedio.setText("Promedio = " + String.valueOf(String.format("%.2f", notas.calcularPromedio())));
        double desv = notas.calcularDesviacion();
        JLDesviacion.setText("Desviacion estandar = " + String.format("%.2f", desv));
        JLMayor.setText("Valor mayor = " + String.valueOf(notas.calcularMayor()));
        JLMenor.setText("Valor menor = " + String.valueOf(notas.calcularMenor()));
    }//GEN-LAST:event_JBCalcularActionPerformed

    private void JBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimpiarActionPerformed
        // TODO add your handling code here:
        JTNota1.setText("");
        JTNota2.setText("");
        JTNota3.setText("");
        JTNota4.setText("");
        JTNota5.setText("");
        JLPromedio.setText("");
        JLDesviacion.setText("");
        JLMayor.setText("");
        JLMenor.setText("");
    }//GEN-LAST:event_JBLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCalcular;
    private javax.swing.JButton JBLimpiar;
    private javax.swing.JLabel JLDesviacion;
    private javax.swing.JLabel JLMayor;
    private javax.swing.JLabel JLMenor;
    private javax.swing.JLabel JLNota1;
    private javax.swing.JLabel JLNota2;
    private javax.swing.JLabel JLNota3;
    private javax.swing.JLabel JLNota4;
    private javax.swing.JLabel JLNota5;
    private javax.swing.JLabel JLPromedio;
    private javax.swing.JTextField JTNota1;
    private javax.swing.JTextField JTNota2;
    private javax.swing.JTextField JTNota3;
    private javax.swing.JTextField JTNota4;
    private javax.swing.JTextField JTNota5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
